import { type NextPage } from "next";
import Head from "next/head";
import { api } from "~/utils/api";

const SinglePostPage: NextPage = () => {
  const { data, isLoading } = api.profile.getUserByUserName.useQuery({
    username: "clothy-terry",
  });

  if (isLoading) return <div>Loading...</div>;

  if (!data) return <div>404</div>;

  console.log(data);
  return (
    <>
      <Head>
        <title>Profile</title>
        <meta name="description" content="Generated by create-t3-app" />
      </Head>
      <main className="flex h-screen justify-center">
        <div>{data.username}</div>
      </main>
    </>
  );
};

export default SinglePostPage;
